apiVersion: apps/v1
kind: Deployment
metadata:
  name: manipulation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manipulation-service
  template:
    metadata:
      labels:
        app: manipulation-service
    spec:
      containers:
        - name: manipulation-service
          image: bitprj/manipulation-service
          ports:
            - containerPort: 80
          env:
            - name: SUBSCRIPTION_KEY
              value: bb8d0b74d8184bd4907793f0d086e313
            - name: ENDPOINT
              value: https://colefaceapi.cognitiveservices.azure.com
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: manipulation-service
spec:
  selector:
    app: manipulation-service
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer